tap 'homebrew/core'
tap 'homebrew/bundle'

# Install GNU core utilities (those that come with macOS are outdated).
brew 'coreutils'
# Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to $PATH.

# Install some other useful utilities like `sponge`.
brew 'moreutils'

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew 'findutils'

# Install GNU `sed`, overwriting the built-in `sed`.
brew 'gnu-sed', args: ['with-default-names']

# Install Bash 4.
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before
# running `chsh`.
brew 'bash'
brew 'bash-completion@2'

# Install `wget` with IRI support.
brew 'wget', args: ['with-iri']

# Install more recent versions of some macOS tools.
brew 'vim', args: ['with-override-system-vi']
brew 'grep'
brew 'openssh'
brew 'screen'

# Install CLI magic.
brew 'z'
brew 'thefuck'

# Install Git tools.
brew 'git'
brew 'git-extras'
brew 'git-flow'
brew 'diff-so-fancy'

# Install Node tools.
brew 'node'
brew 'yarn'
brew 'watchman'

# Install everything else.
brew 'the_silver_searcher'
brew 'httpie'
brew 'lynx'
brew 'rename'
brew 'ruby'
brew 'tree'

# Install native apps from Cask and App Store
tap 'caskroom/cask'
tap 'caskroom/versions'
cask_args appdir: '/Applications'
brew 'mas'

# Install IDEs and dev-related tools.
cask 'visual-studio-code'
cask 'atom'
cask 'sublime-text'
cask 'hyper'
cask 'transmit'
cask 'mamp'

# Install design apps.
mas 'Pixelmator', id: 407963104
cask 'sketch'
cask 'xscope'
cask 'imageoptim'
cask 'imagealpha'

# Install a visual Git tool.
cask 'github-desktop'

# Install browsers.
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'safari-technology-preview'
cask 'opera-beta'
cask 'choosy'

# Install chat apps.
cask 'franz'

# Install media players.
cask 'spotify'
cask 'lastfm'

# Install DVD ripping software.
cask 'ripit'
cask 'handbrake'
mas 'iFlicks 2', id: 731062389

# Install security apps.
mas '1Password', id: 443987910
brew 'gnupg'
cask 'gpg-suite'
cask 'little-snitch'
cask 'micro-snitch'

# Install Quicklook plugins.
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-json'

# Install misc. apps.
cask 'alfred'
mas 'Tweetbot', id: 557168941
mas 'Reeder', id: 880001334
mas 'Things', id: 407951449
mas 'Moom', id: 419330170
mas 'PopClip', id: 445189367
cask 'kap'
cask 'day-o'
mas 'Battery Indicator', id: 1206020918
mas 'The Unarchiver', id: 425424353
mas 'Keynote', id: 409183694
mas 'Mousepose', id: 405904955
mas 'DaisyDisk', id: 411643860
cask 'virtualbox'
cask 'dropbox'
cask 'timemachineeditor'
cask 'appcleaner'
cask 'rowmote-helper'
