tap 'homebrew/core'
tap 'homebrew/bundle'

# Install GNU core utilities (those that come with macOS are outdated).
brew 'coreutils'
# Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to $PATH.

# Install some other useful utilities like `sponge`.
brew 'moreutils'

# Install GNU `find`, `locate`, `updatedb`, `xargs`, and `sed`, but
# `g`-prefixed.
brew 'findutils'
brew 'gnu-sed'

# Install latest Bash and Bash completions.
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before
# running `chsh`.
brew 'bash'
brew 'bash-completion@2'

# Install more recent versions of some macOS tools.
brew 'grep'
brew 'openssh'
brew 'screen'

# Install CLI magic.
brew 'z'
brew 'up'
brew 'thefuck'

# Install Git tools.
brew 'git'
brew 'git-extras'
brew 'git-flow'
brew 'diff-so-fancy'

# Install yarn (and node).
brew 'yarn'

# Install everything else.
brew 'the_silver_searcher'
brew 'httpie'
brew 'lynx'
brew 'rename'
brew 'ruby'
brew 'tree'
brew 'wget'
